### ISSUE TITLE
How to use the `path` function instead of the `url` function in Django?

### ISSUE THREAD

**Issue by newcoderlife** [tomorrow-headline/web#2]
I am learning how to use django-rest-framework to build my front-end separation project. I follow the django official documentation using the path function instead of the url function for development. But when I added django-rest-framework, I found that django-rest-framework is still using the url function. In order to maintain code consistency, I wrote the following code:

In 'quickstart/urls.py'('quickstart' is my app name)

```
from django.urls import path, include
from rest_framework import routers

from quickstart import views

router = routers.DefaultRouter()
router.register('users', views.UserViewSet)
router.register('groups', views.GroupViewSet)

app_name = 'quickstart'
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
]
```

In 'tutorial/urls.py'('tutorial' is project name)

```
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quickstart/', include('quickstart.urls')),
]
```

However, there was a problem with the program. When I visited 127.0.0.1/quickstart/users, I got the following error:

```
Internal Server Error: /quickstart/users/
Traceback (most recent call last):
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\relations.py", line 376, in to_representation
    url = self.get_url(value, self.view_name, request, format)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\relations.py", line 314, in get_url
    return self.reverse(view_name, kwargs=kwargs, request=request, format=format)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\reverse.py", line 50, in reverse
    url = _reverse(viewname, args, kwargs, request, format, **extra)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\reverse.py", line 63, in _reverse
    url = django_reverse(viewname, args=args, kwargs=kwargs, **extra)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\django\urls\resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user-detail' not found. 'user-detail' is not a valid view function or pattern name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\mixins.py", line 48, in list
    return Response(serializer.data)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\serializers.py", line 765, in data
    ret = super(ListSerializer, self).data
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\serializers.py", line 683, in to_representation
    self.child.to_representation(item) for item in iterable
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\serializers.py", line 683, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\serializers.py", line 527, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "C:\dev\tomorrow-headline\venv\lib\site-packages\rest_framework\relations.py", line 391, in to_representation
    raise ImproperlyConfigured(msg % self.view_name)
django.core.exceptions.ImproperlyConfigured: Could not resolve URL for hyperlinked relationship using view name "user-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
[17/Aug/2018 10:33:18] "GET /quickstart/users/ HTTP/1.1" 500 151754
```

This code is completely written in the official django-rest-framework tutorial, just a simple modification of the 'urls' file. So my question is: how to replace the url function with the path function? Do I need to modify the code in other parts?

Thank's a lot.

**Comment by newcoderlife** [comment]
This issue is alse post as a question on [StackOverFlow](https://stackoverflow.com/questions/51887701/how-to-use-the-path-function-instead-of-the-url-function).

**Comment by newcoderlife** [comment]
The project works fine with the following code in tutorial/urls.py:
```
from django.contrib import admin
from django.urls import path, include

from quickstart import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quickstart/', include(urls.urlpatterns)),
]
```
But why?

**Comment by newcoderlife** [comment]
After a period of study, my understanding of `Django` and `django-rest-framework` has gradually deepened. I found that the problem is not in the `url()` function and the `path()` function, but the view has a problem.

In my code, I used `ModelViewSet` to organize my view. I didn't add the `lookup_field` property when writing the `UserViewSet`. This causes the router to handle the request without knowing which url parameter to call the detail part of the `UserViewSet`.

In my code, I added the `lookup_field` property to fix this bug. Code show as below(`views.py`):

    from rest_framework import viewsets
    
    from articles.models import Article
    from articles.serializers import ArticleSerializer
    
    
    class ArticleViewSet(viewsets.ModelViewSet):
        queryset = Article.objects.all()
        serializer_class = ArticleSerializer
    
        lookup_field = 'slug'

I did some refactoring work on the previous code, so the current code might look different from the previous one. But this is no big problem.

**Comment by newcoderlife** [comment]
Another bug that can cause this problem is that the hyperlink variable is defined in the model and viewset, but it is not declared in the serializer. The relevant code is as follows:
```
from rest_framework import serializers

from comments.models import Comment


class CommentSerializer(serializers.HyperlinkedModelSerializer):
    author = serializers.ReadOnlyField(source='author.slug')  # This is important!

    class Meta:
        model = Comment
        fields = ('content', 'author', )

```
